/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val member1= Member("M1", "S", "s")
    member1.setName("Smith")
    member1.setEmail("smith.com")
    member1.setEmail("smith@gmail.com")

    val book1 = Book("B1", "Harry Potter", "JK", "1111-222", 122)
    member1.borrowItem(book1)

    val member2 = Member("M2", "John", "john@gmail.com")
    member2.borrowItem(book1)

    member2.returnItem(book1)
    member1.returnItem(book1)
    member2.borrowItem(book1)
    member1.totalLateFees(15)
    member2.totalLateFees(15)

}
